#!/bin/bash

shopt -s extglob
export LC_COLLATE=C

# menu_1
PS3="Enter Your Choice: "
select var in 'Create Database' 'List Databases' 'Connect To Databases' 'Drop Database' 'exit'
do 

case $var in
"exit")	
	break
	;;

"Create Database")
    while true
    do
        read -p "Enter Datbase Name: " DBName
        if [[ $DBName =~ ^[A-Z]?[a-z_]*[a-z]$ ]]
        then
                if [[ ! -e $DBName ]]
                then
                    mkdir ./$DBName
                    echo Database successfully created!
                    break
                else
                    echo Database Already Exist!
                fi    
        else
            echo Enter a Valid Name!    
       
        fi    
    done 
    ;;  
    
    

"List Databases")
    declare -i count=0
	for dir in $(ls -l | grep ^d | awk '{print $9}' | sort -f)

    do
    count+=1
        echo $count")" $dir
    done    
	;;
    
"Connect To Databases")
	echo Connect To Databases
	;;

"Drop Database")
	echo Drop Database
	;;

*)
	echo Enter a Valid Number!
	;;

esac

done 

